# -*- coding: utf-8 -*-
"""ism_precipitation_and_applicationRate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ug2Jr3efgqHHIHXAoeed2MkwN4EGmGiZ

#Constant numbers
"""

FlowRateUnits = {'gpm': 1,
                 'gph': .016666666666667,
                 'gpd': .000694444,
                 'acre-in/day': 18.85714,
                 'acre-in/hr': 452.5714,
                 'acre-ft/day': 226.2857,
                 'lps': 15.85032,
                 'lpm': .264172051,
                 'lph': .004402868,
                 'lpd': .000183453,
                 'cms': 15850.32314,
                 'cfs': 448.8311688,
                 'cu. m/hr': 4.402867521
                } #gpm per unit
AreaUnits = {'acre': 1,
             'sq. in.': 6272640,
             'sq. ft.': 43560,
             'hectare': .404685658,
             'sq. cm.': 40468564.224,
             'sq. meter': 4046.856579,
             'sq. yd': 4840,
             'sq. km': 0.004046856422,
             'sq. mile': 0.0015625
             } #unit per acre
DiameterUnits = {'cm': 1,
                 'mm': 0.1,
                 'in': 2.54,
                 '8ths in': .3175,
                 '16ths in': .15875,
                 '32nds in': .079375,
                 '64ths in': .0396875,
                 '128ths in': .01984375
                 } #cm per unit
PressureUnits = {'psi': 1,
                 'bar': 0.068947573,
                 'kPa': 6.8947625,
                 'ft': 2.306661407,
                 'm': .703249615
                 } #psi per unit
HeadSpacingUnits = {'ft': 1,
                    'm': .3048} #unit per ft
LineSpacingUnits = HeadSpacingUnits
DistanceUnits = {'cm': 1,
                 'in': 2.54,
                 'ft': 30.48,
                 'm': 100
                } #cm per unit
SpacingUnits = DistanceUnits
# List of keys to include in the new dictionary
emitterFlow_keys = ['gpm','gph','lpm','lps']
EmitterFlowUnits = {}
for key in emitterFlow_keys:
    EmitterFlowUnits[key] = FlowRateUnits[key]

nozzleFlowRate_keys = ['gpm','acre-in/day','acre-in/hr','acre-ft/day','lps','lpm','lph']
NozzleFlowRateUnits = {}
for key in nozzleFlowRate_keys:
    NozzleFlowRateUnits[key] = FlowRateUnits[key]

def calc_applicationRate(flowRateUnits,flowRate,areaUnits,area,efficiency):
  flowRate *= FlowRateUnits[flowRateUnits]                                      #to gpm
  area /= AreaUnits[areaUnits]                                                  #to acre
  applicationRate = flowRate/area*efficiency/100
  applicationRate /= 452.57                                                     #to in/hr
  IrrApRt = applicationRate
  return IrrApRt                                                                #in/hr

def calc_dripRate(emitterFlowUnits,emitterFlow,spacingUnits,spacing,
                  distanceUnits,distance,DripEff):
            emitterFlow *= EmitterFlowUnits[emitterFlowUnits]                         #to gpm
            spacing *= SpacingUnits[spacingUnits]                                     #to cm
            distance *= DistanceUnits[distanceUnits]                                  #to cm
            appRate = (spacing/2.54)*(distance/2.54)*DripEff/100
            appRate = (231*emitterFlow*60)/appRate
            IrrApRt = appRate
            return IrrApRt                                                            #in/hr

import math
def calc_precipitation(diameterUnits,diameter,
                       pressureUnits,pressure,
                       headSpacingUnits,headSpacing,
                       lineSpacingUnits,lineSpacing,
                       nozzleFlowRateUnits,
                       efficiency):
  diameter *= DiameterUnits[diameterUnits]                                      #cm
  pressure /= PressureUnits[pressureUnits]                                      #psi
  headSpacing /= HeadSpacingUnits[headSpacingUnits]                             #ft
  lineSpacing /= LineSpacingUnits[lineSpacingUnits]                             #ft
  #nozzleFlowRate = diameter/2.54                                               #inch
  #nozzleFlowRate = 28.925*math.sqrt(pressure)*math.pow(nozzleFlowRate,2)
  #nozzleFlowRate /= NozzleFlowRateUnits[nozzleFlowRateUnits]                   #seems no need

  nozzleAppRate = diameter/2.54                                                 #inch
  nozzleAppRate = math.pow(nozzleAppRate,2)
  nozzleAppRate = 28.925*math.sqrt(pressure)*nozzleAppRate                      #gpm
  nozzleAppRate = nozzleAppRate/((lineSpacing*headSpacing)/efficiency*100)
  nozzleAppRate *= 96.25025
  IrrApRt = nozzleAppRate                                                       #in/hr
  return IrrApRt