# -*- coding: utf-8 -*-
"""ISM_default_parameters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drG2Tmy1WfBvKEbpKb-lKUmUtdXc1jYy
"""
import pandas as pd

defaultPath = "./irrigationtables"

cropparameterfile = f'{defaultPath}/tblcropdefaults.csv'
soilparameterfile = f'{defaultPath}/tblsoildefaults.csv'
cropregionfile = f'{defaultPath}/table_cropRegion.csv'
stationregionfile = f'{defaultPath}/table_station2region.csv'
agweathernetstationfile = f'{defaultPath}/AgWeatherNet   Washington State UniversityWSU Cougar HeadWSU Cougar Head.csv'

cropparameter = pd.read_csv(cropparameterfile,sep=';', header=0)
soilparameter = pd.read_csv(soilparameterfile,sep=';', header=0)
cropregion = pd.read_csv(cropregionfile,sep=';', header=0)
stationregion = pd.read_csv(stationregionfile,sep=';', header=0)
agweathernetstation = pd.read_csv(agweathernetstationfile,sep=',', header=0)

cropparameter = cropparameter.set_index('cropDefaultsID')
soilparameter = soilparameter.set_index('soilID')
agweathernetstation = agweathernetstation.set_index('Station ID')