# -*- coding: utf-8 -*-
"""convert_netcdf_to_VIC_binary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0ALo2l6Hnroish8POo4eUs2h9gheGgv
"""

#!pip install xarray fsspec netCDF4 --quiet
import xarray as xr
import fsspec
import matplotlib.pyplot as plt

import os
import numpy as np
def compute_daily_rh(q, ta, pressure, varname):
    """
    Compute daily minimum relative humidity from specific humidity and Tmax.
    Parameters:
    ----------
    q : specific humidity variable
    ta : air temperture variable (daily temperature in K).
    pressure : Surface pressure in Pascals (default is 101325 Pa).
    Returns:
    -------
    xarray.Dataset
        Dataset with a new variable 'rhmin' (%).
    """
    # Actual vapor pressure (Pa)
    e = (q * pressure) / (0.622 + 0.378 * q)
    # Saturation vapor pressure at Tmax (Pa)
    tair = ta - 273.15
    es = 6.112 * np.exp((17.67 * tair) / (tair + 243.5)) * 100.
    # RHmin (%)
    rh = (e / es) * 100.
    #rh.name = rh
    #rh = rh.assign(rhmin=rhmin)
    rh.attrs['units'] = '%'
    rh.attrs['long_name'] = 'Daily Relative Humidity'
    #print(rh)
    #print(rh.data_vars)
    #old_name = list(rh.data_vars)[0]
    #rh = rh.rename({old_name: varname})

    return rh

droot = 'https://hydrology.soton.ac.uk/data/pgf/v3/0.25deg/daily'
vars = ['dlwrf','dswrf','pres','prcp','shum','tas','tmax','tmin','wind']
#unit: W/m2, pa, mm/s, kg/kg, K, m/s

#subset data sets
lat_min,lat_max,lon_min,lon_max = 27,41,35,49
outpath_raw = '/media/liuming/USB1TB1/Salah/pgf_v3_0.25_nc'
outpath_bin = '/media/liuming/USB1TB1/Salah/pgf_v3_0.25_bin'

vic_vars = {'PREC':40,'TMAX':100,'TMIN':100,'WIND':100,'QAIR':10000,'SHORTWAVE':40,'RHUM_MAX':100,'RHUM_MIN':100}
#unit: {mm/day,Celsius degree, Celsius degree, m/s,kg/kg,W/m2,%,%}

remove_original = False

"""Source:         Princeton University
Name:           Princeton Global Forcings
Period:         Jan-1948 - Dec-2016
Times:          3-hourly, daily, monthly
Coverage:       Global
Resolution:     0.25-degree
Grid:           Latitude-longitude
Type:           Observational-Reanalysis hybrid
Related Sites:	http://hydrology.princeton.edu/data/index.html
Publications:   Sheffield, J., G. Goteti, and E. F. Wood, Development of a
		50-yr high-resolution global dataset of meteorological forcings for land
		surface modeling, J. Climate, 19 (13), 3088-3111.
Variables:	Precipitation (prcp)
		Air temperature at 2m above ground (tas)
		Downward longwave at surface (dlwrf)
		Downward shortwave at surface (dswrf)
		Surface pressure (pres)
		Specific humidity (shum)
		Windspeed (wind)
Formats:        NetCDF
History:	Original data version 1 (V1) and updates (V2, V2.2, V3)
Volume:         3hourly:
		0.25deg: 5-8 GB/year/variable; daily: 0.5-1.0 GB/year/variable; monthly: 0.01 GB/year/variable
Date Created:   Tue May 29 00:00:00 EDT 2018
Change Log:     

1) Tue May 29 00:00:00 EDT 2018
New version V3 added to website
V3 is 0.25-degree, 3-hourly, semi-global, 1948-2016
It contains a number of upgrades including
- extension to 2016
- updated method for rain day correction
- many others (to be documented here)
"""

elev = 'https://hydrology.soton.ac.uk/data/pgf/elevation_0.25deg.nc'
#elevation as a test
# Replace this with your NetCDF file URL
url = f"{elev}"
# Open the dataset
# Use fsspec to open the remote file
with fsspec.open(url) as f:
    ds = xr.open_dataset(f, engine="scipy")
# Check contents
print(ds)
# Select the only time and z index
elev_2d = ds['elev'].isel(time=0, z=0)
# Plot using xarray’s built-in plotting
elev_2d.plot(cmap="terrain")
plt.title("Elevation (m)")
plt.show()

"""VIC: binaries
N_TYPES            8            # Number of variables (columns)
FORCE_TYPE        PREC    UNSIGNED    40
FORCE_TYPE        TMAX    SIGNED        100
FORCE_TYPE        TMIN    SIGNED        100
FORCE_TYPE        WIND    SIGNED        100
FORCE_TYPE      QAIR    SIGNED          10000
FORCE_TYPE      SHORTWAVE       SIGNED          40
FORCE_TYPE      RHUM_MAX        SIGNED          100
FORCE_TYPE      RHUM_MIN        SIGNED          100

unit: {mm/day,Celsius degree, Celsius degree, m/s,kg/kg,W/m2,%,%}

latitude: array([-89.875, -89.625, -89.375, ...,  89.375,  89.625,  89.875]
longitude: 'array([1.25000e-01, 3.75000e-01, 6.25000e-01, ..., 3.59375e+02, 3.59625e+02,
       3.59875e+02]
"""



"""Downloading data and clip the target domain"""

import requests
import time
import struct
for year in range(1983,2017):
  print(f'Year: {year}')
  for var in vars: #['dlwrf','dswrf','pres','prcp','shum','tas','tmax','tmin','wind']
    if True: #and var == 'tas':
      fname = f"{var}_daily_{year}-{year}.nc"
      #temporally download the data file
      url = f"{droot}/{fname}"
      if not os.path.exists(f'{outpath_raw}/{fname}') and not os.path.exists(f'{outpath_raw}/EuTr_{fname}'):
        print(f'Downloading {url}')
        response = requests.get(url)
        with open(f'{outpath_raw}/{fname}', "wb") as f:
            f.write(response.content)

      if os.path.exists(f'{outpath_raw}/{fname}') and not os.path.exists(f'{outpath_raw}/EuTr_{fname}'):
        # Open the downloaded NetCDF file using xarray
        ds = xr.open_dataset(f'{outpath_raw}/{fname}', engine="netcdf4")
        #print(ds)
        ds = ds.assign_coords(lon=(((ds.lon + 180) % 360) - 180))
        # Now sort the longitudes so they are in increasing order
        ds = ds.sortby('lon')
        t = ds.sel(lat=slice(lat_min, lat_max), lon=slice(lon_min, lon_max))

        #save subset
        t.to_netcdf(f'{outpath_raw}/EuTr_{fname}')
        #remove original
        if remove_original == True:
          os.remove(f'{outpath_raw}/{fname}')

import requests
import time
import struct
import os

for year in range(1948,2017):
  print(f'Year: {year}')
  ds_subset = dict()
  for var in vars: #['dlwrf','dswrf','pres','prcp','shum','tas','tmax','tmin','wind']
    if True: #and var == 'tas':
      fname = f"{var}_daily_{year}-{year}.nc"

      #temporally download the data file
      url = f"{droot}/{fname}"
      if not os.path.exists(f'{outpath_raw}/{fname}') and not os.path.exists(f'{outpath_raw}/EuTr_{fname}'):
        print(f'Downloading {url}')
        response = requests.get(url)
        with open(f'{outpath_raw}/{fname}', "wb") as f:
            f.write(response.content)

      if os.path.exists(f'{outpath_raw}/{fname}') and not os.path.exists(f'{outpath_raw}/EuTr_{fname}'):
        # Open the downloaded NetCDF file using xarray
        ds = xr.open_dataset(f'{outpath_raw}/{fname}', engine="netcdf4")
        #print(ds)
        ds = ds.assign_coords(lon=(((ds.lon + 180) % 360) - 180))
        # Now sort the longitudes so they are in increasing order
        ds = ds.sortby('lon')
        ds_subset[var] = ds.sel(lat=slice(lat_min, lat_max), lon=slice(lon_min, lon_max))

        #save subset
        ds_subset[var].to_netcdf(f'{outpath_raw}/EuTr_{fname}')
        #remove original
        os.remove(f'{outpath_raw}/{fname}')
      elif os.path.exists(f'{outpath_raw}/EuTr_{fname}'):
        ds_subset[var] = xr.open_dataset(f'{outpath_raw}/EuTr_{fname}', engine="netcdf4")

      '''
      #print(ds_subset[var])
      if var == 'prcp':
        t_mean = ds_subset[var][var].mean(dim='time') * 3600 * 24 * 365.25 # (lat, lon) #ds_subset[var][var].mean(dim='time')
      else:
        t_mean = ds_subset[var][var].mean(dim='time')
        # Plot the result
      t_mean.plot(cmap='coolwarm')
      plt.title(var)
      plt.show()
      '''
  if ds_subset:
    vic_subset = dict()
    for vvar in ['PREC','TMAX','TMIN','WIND','QAIR','SHORTWAVE']:
      if vvar == 'PREC':
        vic_subset[vvar] = ds_subset['prcp']['prcp'] * 3600. * 24. * vic_vars[vvar]
      elif vvar == 'TMAX':
        vic_subset[vvar] = (ds_subset['tmax']['tmax'] - 273.15) * vic_vars[vvar]
      elif vvar == 'TMIN':
        vic_subset[vvar] = (ds_subset['tmin']['tmin'] - 273.15) * vic_vars[vvar]
      elif vvar == 'WIND':
        vic_subset[vvar] = ds_subset['wind']['wind'] * vic_vars[vvar]
      elif vvar == 'QAIR':
        vic_subset[vvar] = ds_subset['shum']['shum'] * vic_vars[vvar]
      elif vvar == 'SHORTWAVE':
        vic_subset[vvar] = ds_subset['dswrf']['dswrf'] * vic_vars[vvar]

    for vvar in ['RHUM_MAX','RHUM_MIN']:
      if vvar == 'RHUM_MAX':
        vic_subset[vvar] = compute_daily_rh(ds_subset['shum']['shum'], ds_subset['tmin']['tmin'], ds_subset['pres']['pres'], vvar).clip(max=100) * vic_vars[vvar]
      if vvar == 'RHUM_MIN':
        vic_subset[vvar] = compute_daily_rh(ds_subset['shum']['shum'], ds_subset['tmax']['tmax'], ds_subset['pres']['pres'], vvar).clip(max=100) * vic_vars[vvar]

    for i in range(len(vic_subset['PREC']['lat'])):
      lat = vic_subset['PREC']['lat'].values[i]
      for j in range(len(vic_subset['PREC']['lon'])):
        lon = vic_subset['PREC']['lon'].values[j]
        val = vic_subset['PREC'].isel(lat=i, lon=j, time=0).item()
        if val is not None and not np.isnan(val):
          bfile = f'{outpath_bin}/data_{lat:.3f}_{lon:.3f}'
          print(f'{year} data_{lat:.3f}_{lon:.3f}')
          #if from the first year, remove the existing file
          if year == 1948 and os.path.exists(bfile):
            os.remove(bfile)

          #Create and append new file
          with open(bfile, 'ab') as f:
            dlist = list()
            fmt = ''
            for t in range(len(vic_subset['PREC']['time'])):
              #print(t)
              for vvar in ['PREC','TMAX','TMIN','WIND','QAIR','SHORTWAVE','RHUM_MAX','RHUM_MIN']:
                tval = vic_subset[vvar].isel(lat=i, lon=j, time=t).item()
                dlist.append(int(tval))
                #print(f'{lat:.3f} {lon:.3f} {t} {vvar} {tval / vic_vars[vvar]}')
                #if vvar == 'PREC':
                #  f.write(struct.pack('I', int(tval)))
                #else:
                #  f.write(struct.pack('i', int(tval)))
              fmt += 'Hhhhhhhh'
            f.write(struct.pack(fmt, *dlist))