# -*- coding: utf-8 -*-
"""generate_VIC_CropSyst_rotation_files_from_state_outputs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18DVip-kWK26HXj7dN-OBfqN9DXXwr9sP
"""

# Cell 1 — imports and configurable paths
import os
import re
import glob
import shutil
import datetime
import argparse
import pandas as pd

parser = argparse.ArgumentParser(description="Generate updated CS_rotation files for a warm-restart run.")
parser.add_argument("--state_csv", type=str,
                     default="",
                     help="Path to the state-output CSV (e.g. branch_point_19850710_crop.csv)")
parser.add_argument("--vegparam", type=str,
                     default="",
                     help="Path to vegparam.txt")
parser.add_argument("--orig_rotation_path", type=str,
                     default="",
                     help="Directory containing the original .CS_rotation files")
parser.add_argument("--updated_rotation_path", type=str,
                     default="",
                     help="Output directory for the updated .CS_rotation files")

# parse_known_args() ignores Colab's own injected argv (e.g. -f kernel.json),
# so this cell works whether run interactively or via `!python pipeline.py --key value`
args, _ = parser.parse_known_args()

STATE_CSV              = args.state_csv
VEGPARAM                = args.vegparam
ORIG_ROTATION_PATH      = args.orig_rotation_path
UPDATED_ROTATION_PATH   = args.updated_rotation_path

os.makedirs(UPDATED_ROTATION_PATH, exist_ok=True)

print(f"STATE_CSV             = {STATE_CSV}")
print(f"VEGPARAM               = {VEGPARAM}")
print(f"ORIG_ROTATION_PATH     = {ORIG_ROTATION_PATH}")
print(f"UPDATED_ROTATION_PATH  = {UPDATED_ROTATION_PATH}")

# Cell 2 — parse vegparam.txt into {cellnum: [veg_code, veg_code, ...]}
# Each cell block is: "cellnum nvegs" header, then nvegs pairs of
# (class-param line, monthly-LAI line). veg_index in the state output
# is the 0-based position of a veg within this ordered list.

def parse_vegparam(path):
    veg_by_cell = {}
    with open(path) as f:
        lines = [ln.rstrip("\n") for ln in f]

    i, n = 0, len(lines)
    while i < n:
        line = lines[i].strip()
        if not line:
            i += 1
            continue
        parts = line.split()
        cellnum, nvegs = int(parts[0]), int(parts[1])
        i += 1
        codes = []
        for _ in range(nvegs):
            veg_line = lines[i].strip().split()
            codes.append(veg_line[0])   # veg class code, e.g. "1401"
            i += 2                      # skip class line + its LAI line
        veg_by_cell[cellnum] = codes
    return veg_by_cell

veg_by_cell = parse_vegparam(VEGPARAM)
#veg_by_cell

# Cell 3 — load the state output, keep only is_active == 1 rows
df = pd.read_csv(STATE_CSV)
active = df[df["is_active"] == 1].copy()
#active

# Cell 4 — map (cellnum, veg_index) -> veg code from vegparam.txt
def lookup_veg_code(row):
    codes = veg_by_cell.get(int(row["cellnum"]))
    if codes is None:
        return None
    idx = int(row["veg_index"])
    return codes[idx] if 0 <= idx < len(codes) else None

active["rotation_code"] = active.apply(lookup_veg_code, axis=1)
#active[["date", "cellnum", "veg_index", "crop_code", "rotation_code"]]

# Cell 5 — dedup to get the final list of crop codes needing a sowing-date reset
rotation_codes = sorted(set(active["rotation_code"].dropna()), key=lambda x: int(x))
print("Crop rotation codes needing sowing date reset:", rotation_codes)

# Cell 6 — update / copy CS_rotation files, handling both single-crop
# and two-crop (two [sowing:N] sections) rotation files

import os
import re
import glob
import shutil
import datetime

# --- dates from the state file ---
branch_date  = pd.to_datetime(df["date"].iloc[0]).date()      # e.g. 1985-07-10
state_doy    = branch_date.timetuple().tm_yday                # e.g. 191 -- used for the decision logic
restart_date = branch_date + datetime.timedelta(days=1)
restart_doy_str = f"{restart_date.timetuple().tm_yday:04d}"   # e.g. "0192" -- the value we write in
print(f"branch_date={branch_date}  state_doy={state_doy}  restart_doy={restart_doy_str}")

JULY1_DOY = 182  # non-leap-year day-of-year for July 1, consistent with the rest of the pipeline

def find_sowing_sections(content):
    """Split a .CS_rotation file into its [sowing:N] blocks."""
    matches = list(re.finditer(r"\[sowing:(\d+)\]", content))
    sections = []
    for i, m in enumerate(matches):
        start = m.start()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(content)
        sections.append({"num": int(m.group(1)), "start": start, "end": end, "text": content[start:end]})
    return sections

def section_date(section_text):
    m = re.search(r"^date=(\d+)", section_text, re.MULTILINE)
    return int(m.group(1)) if m else None

def replace_section_dates(section_text, new_doy_str):
    """Update both event_date= and date= within a single section's text."""
    text = re.sub(r"^event_date=\d+", f"event_date={new_doy_str}", section_text, flags=re.MULTILINE)
    text = re.sub(r"^date=\d+", f"date={new_doy_str}", text, flags=re.MULTILINE)
    return text

def choose_section_to_update(sections, state_doy):
    """Decide which [sowing:N] section is the one that's currently growing."""
    if len(sections) == 1:
        return sections[0]["num"]
    if len(sections) != 2:
        return None  # only 1- and 2-crop rotations are handled by these rules

    first, second = sorted(sections, key=lambda s: s["num"])
    first_doy, second_doy = section_date(first["text"]), section_date(second["text"])

    if first_doy < JULY1_DOY:
        # both crops sown within the same calendar-year window
        if first_doy <= state_doy <= second_doy:
            return first["num"]
        elif state_doy > second_doy or state_doy < first_doy: #might be next year before first crop sow
            return second["num"]
        else:
            return None  #needs manual review
    elif first_doy >= JULY1_DOY and second_doy < JULY1_DOY:
        # rotation spans a calendar-year boundary (e.g. fall-sown -> spring-sown)
        if state_doy >= first_doy or state_doy <= second_doy:
            return first["num"]
        elif second_doy <= state_doy <= first_doy:
            return second["num"]
        else:
            return None
    else:
        return None  # configuration not covered by the given rules

for src_path in glob.glob(os.path.join(ORIG_ROTATION_PATH, "*.CS_rotation")):
    fname = os.path.basename(src_path)
    code = fname[: -len(".CS_rotation")]
    dst_path = os.path.join(UPDATED_ROTATION_PATH, fname)

    if code not in rotation_codes:
        shutil.copy2(src_path, dst_path)
        print(f"  copied {fname} unchanged (code not active)")
        continue

    with open(src_path) as f:
        content = f.read()

    sections = find_sowing_sections(content)
    if not sections:
        print(f"  WARNING: no [sowing:N] section found in {fname}; copying unchanged")
        shutil.copy2(src_path, dst_path)
        continue

    target_num = choose_section_to_update(sections, state_doy)
    if target_num is None:
        print(f"  WARNING: could not determine which sowing section to update in {fname}; copying unchanged")
        shutil.copy2(src_path, dst_path)
        continue

    target = next(s for s in sections if s["num"] == target_num)
    new_section_text = replace_section_dates(target["text"], restart_doy_str)
    new_content = content[:target["start"]] + new_section_text + content[target["end"]:]

    with open(dst_path, "w") as f:
        f.write(new_content)
    print(f"  updated {fname}: [sowing:{target_num}] date -> {restart_doy_str}")
